language: node_js
node_js:
- '0.10'


addons:
  code_climate:
    repo_token:
      # CODECLIMATE_REPO_TOKEN
      secure: f9igQcXZoWEEXJg30uSRE3FQiIZ3KoQab2Myo/ye6rpauuSVCKfelLyaNwx5A/a1XuGrL0pnHiRD11+h1lDcGbFVmEc08J0Ah7e9MQQGNWZ/Gg6lkPl56y/uwNSJHVDLHW/yPjSIFMM5KQ0EPlpvroLIbjqg9LUFezgi4YtG8d0=


before_install:
  - npm install -g npm
  - npm install -g codeclimate-test-reporter

install:
  - npm install

script:
  - npm run test

after_success:
  - npm run cover-lcov
  - codeclimate < ./coverage/lcov.info


deploy:
  provider: npm
  email: aymeric@beaumet.me
  api_key:
    secure: hhLLSmks10XtfRTetsQNyNahCl/VN1GkX4TgEXTIpWZ9QWzp2UuA2emSPH5LButw/TYmEBFoMKrxi/GGGCi0NSxcyDVjjDRjo+VyQcJML+atkwF20YmMZ12CpG+aSs3mQLZQLXKWtPYj0gR9tNnEh3sRYX0XkRxKDdLDC+4//xs=
  on:
    repo: agitojs/agito-json-loader
    #on: master
    all_branches: true # Travis issue, should not be necessary
    tags: true
